server:
  port: 7003  #通过7001将注册中心启动

#Eureka注册中心的配置
eureka:
  instance:
    hostname: eureka7003.com  # Eureka服务端的主机，我们也可以自己配置一个伪网址
    #    hostname: 172.17.0.2  # Eureka服务端的主机，我们也可以自己配置一个伪网址
    prefer-ip-address: false
  client:
    register-with-eureka: true #true   #是否要向Eureka注册中心注册自己，自己是服务端，所以设定为false意味着不需要
    fetch-registry: true  #true表示客户端,false是注册中心服务端,单注册中心的时候就为false，集群注册中心的时候就要为true
    service-url: #注册中心监控页面的网址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  #      defaultZone: http://172.17.0.3:7002/eureka/
  server:
    enable-self-preservation: true #关闭自我保护机制

spring:
  application:
    name: eureka-service
  cloud:
    inetutils:
      timeout-seconds: 10